/** Core domain model for GET.teksi. */

export type LatLng = { lat: number; lng: number }

export type Place = {
  id: string
  name: string
  address: string
  coord: LatLng
  category?: 'airport' | 'mall' | 'transit' | 'landmark' | 'area' | 'recent' | 'saved'
}

/** The service verticals inDrive exposes. */
export type ServiceType = 'city' | 'intercity' | 'delivery' | 'freight' | 'moto'

export type VehicleClass = 'economy' | 'comfort' | 'xl'

export type PaymentMethod = 'cash' | 'card' | 'wallet'

export type Role = 'passenger' | 'driver'

export type User = {
  id: string
  phone: string
  name: string
  email?: string
  avatarColor: string
  createdAt: number
  /** Passenger-side rating. */
  rating: number
  ridesTaken: number
  /** Present once the user has completed driver onboarding. */
  driverProfile?: DriverProfile
  walletBalance: number
  homePlace?: Place
  workPlace?: Place
}

export type DriverProfile = {
  vehicle: Vehicle
  rating: number
  ridesGiven: number
  /** Lifetime gross earnings, minor units of the local currency. */
  earnings: number
  verified: boolean
  documents: DriverDocument[]
  joinedAt: number
}

export type Vehicle = {
  make: string
  model: string
  year: number
  color: string
  plate: string
  vehicleClass: VehicleClass
  seats: number
}

export type DriverDocument = {
  id: string
  kind: 'license' | 'registration' | 'insurance' | 'psv' | 'selfie'
  label: string
  status: 'missing' | 'pending' | 'approved' | 'rejected'
  expiresAt?: number
}

/**
 * A driver visible on the map. Bot drivers are generated by the simulation
 * engine; real drivers broadcast themselves over the backend channel.
 */
export type NearbyDriver = {
  id: string
  name: string
  avatarColor: string
  rating: number
  ridesGiven: number
  vehicle: Vehicle
  coord: LatLng
  /** Heading in degrees, used to rotate the car marker. */
  bearing: number
  isBot: boolean
}

export type RideStatus =
  /** Passenger is composing the order (client-side only). */
  | 'draft'
  /** Published; drivers may bid. */
  | 'searching'
  /** Passenger accepted an offer; driver is heading to pickup. */
  | 'accepted'
  | 'arriving'
  | 'waiting'
  | 'in_progress'
  | 'completed'
  | 'cancelled'

export type CancelledBy = 'passenger' | 'driver' | 'system'

/** A driver's bid on a ride request — the heart of the inDrive model. */
export type Offer = {
  id: string
  rideId: string
  driverId: string
  driverName: string
  driverAvatarColor: string
  driverRating: number
  driverRidesGiven: number
  vehicle: Vehicle
  /** Bid amount in minor units (sen). */
  price: number
  /** Minutes until the driver reaches pickup. */
  etaMinutes: number
  /** Straight-line km from driver to pickup at bid time. */
  distanceKm: number
  createdAt: number
  /** Bids auto-expire so a stale list never blocks the passenger. */
  expiresAt: number
  status: 'pending' | 'accepted' | 'declined' | 'expired' | 'withdrawn'
  /** True when the driver took the passenger's asking price unchanged. */
  matchedAskingPrice: boolean
}

export type Ride = {
  id: string
  passengerId: string
  passengerName: string
  passengerAvatarColor: string
  passengerRating: number
  service: ServiceType
  vehicleClass: VehicleClass
  pickup: Place
  dropoff: Place
  /** Optional mid-route stop. */
  stop?: Place
  /** Passenger's asking fare, minor units. Raised via "raise price". */
  askingPrice: number
  /** What the ride actually settled at (the accepted offer's price). */
  finalPrice?: number
  recommendedPrice: number
  currency: string
  distanceKm: number
  durationMinutes: number
  paymentMethod: PaymentMethod
  passengerCount: number
  comment?: string
  options: RideOption[]
  status: RideStatus
  createdAt: number
  updatedAt: number
  /** Set once an offer is accepted. */
  driverId?: string
  driverName?: string
  driverAvatarColor?: string
  driverRating?: number
  driverVehicle?: Vehicle
  driverCoord?: LatLng
  driverBearing?: number
  /** Timeline stamps, used for receipts and the ride summary. */
  acceptedAt?: number
  arrivedAt?: number
  startedAt?: number
  completedAt?: number
  cancelledAt?: number
  cancelledBy?: CancelledBy
  cancelReason?: string
  /** Route geometry from pickup to dropoff, for the map polyline. */
  routeGeometry?: LatLng[]
  /** Number of times the passenger bumped their asking price. */
  priceRaises: number
  ratingByPassenger?: RideRating
  ratingByDriver?: RideRating
  tip?: number
}

export type RideOption =
  | 'child_seat'
  | 'pet'
  | 'luggage'
  | 'air_con'
  | 'no_smoking'
  | 'silent_ride'
  | 'female_driver'

export type RideRating = {
  stars: number
  tags: string[]
  comment?: string
  createdAt: number
}

export type ChatMessage = {
  id: string
  rideId: string
  from: Role
  text: string
  createdAt: number
  read: boolean
}

export type Notification = {
  id: string
  title: string
  body: string
  createdAt: number
  read: boolean
  kind: 'ride' | 'promo' | 'system' | 'safety'
  rideId?: string
}

export type PromoCode = {
  code: string
  label: string
  /** Percentage off, 0-100. */
  percentOff?: number
  /** Flat discount in minor units. */
  amountOff?: number
  minSpend?: number
  expiresAt: number
}

export type Transaction = {
  id: string
  kind: 'ride_payment' | 'ride_earning' | 'topup' | 'payout' | 'tip' | 'promo'
  amount: number
  description: string
  createdAt: number
  rideId?: string
}

/** Emitted onto the realtime bus so both roles stay in sync across tabs. */
export type BusEvent =
  | { type: 'ride:published'; ride: Ride }
  | { type: 'ride:updated'; ride: Ride }
  | { type: 'ride:cancelled'; rideId: string; by: CancelledBy; reason?: string }
  | { type: 'offer:created'; offer: Offer }
  | { type: 'offer:updated'; offer: Offer }
  | { type: 'chat:message'; message: ChatMessage }
  | { type: 'driver:location'; driverId: string; coord: LatLng; bearing: number }
